1.min() => returns the minimum element from the array.

2.max() => returns the maximum element from the array.

3.argmin() => return the index of min value in the array.

4.argmax() => returns the index of the max value in the array.

5.sqrt() => returns the square root of each elemnt present in the array.

6.sin() => returns the sin value of each elemnts of the array.

7.cos() => returns the cos value of each element of the array.

8. sum() = > returns the sum of all elemnts in the array

In [1]:
import numpy as np
arr = np.array([10,20,30,40,67,5,70,80,90])
print("The maximum elemnt in the array is: ",np.max(arr))
print("The minimum element in the array is: ",np.min(arr))
print("index of max elemnt is: ",np.argmax(arr))
print("index of the min elemnt is: ",np.argmin(arr))
print("Sum of all the element of array is: ",np.sum(arr))
print("Square root of each elemnts in the array is: \n",np.sqrt(arr))
print("the sine value of element in array is: \n",np.sin(arr))
print("The cos value of element in array is: \n",np.cos(arr))

The maximum elemnt in the array is:  90
The minimum element in the array is:  5
index of max elemnt is:  8
index of the min elemnt is:  5
Sum of all the element of array is:  412
Square root of each elemnts in the array is: 
 [3.16227766 4.47213595 5.47722558 6.32455532 8.18535277 2.23606798
 8.36660027 8.94427191 9.48683298]
the sine value of element in array is: 
 [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.85551998 -0.95892427
  0.77389068 -0.99388865  0.89399666]
The cos value of element in array is: 
 [-0.83907153  0.40808206  0.15425145 -0.66693806 -0.5177698   0.28366219
  0.6333192  -0.11038724 -0.44807362]


VVI

9 .linespace(start , end, total_no_of_values) => returns an array having specific number of points, evenly distributed b/w two values.

i.e return value of a given range and with a same gap b/w consecutive elements.

In [11]:
import numpy as np
arr = np.linspace(1,2,5)
# here it will return an array of 5 elements b/w 1 to 2 including both
print(arr)

[1.   1.25 1.5  1.75 2.  ]


Applying array function on 2D array.
1. min(array_name, axis = 1) => it return the row wise minimum value.
in the form of array.

2. min(array_name, axis = 0) => it return the column wise minimum value.
in the form of array.

3. max(array_name, axis = 0) => it return the column wise maximum value.
in the form of array.

4. max(array_name, axis = 1) => it return the row wise maximum value.
in the form of array.

5. sum(array_name, axis = 1) => it returns the row wise sum of elements.
in the form of array.

6. sum(array_name, axis = 0) => it returns the column wise sum of elements.
in the form of array.

7. cumsum(array_name) => it returns an array of sum of elemnts present before them (for ex:- arr = [1,2,3] then the result would be : [1,3,6]).

In [45]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(1,21,9).reshape(3,3)
arr = np.array(arr)
print(arr)
print("The maximum element in the array is: ",np.max(arr)," and present on index: ",np.argmax(arr))
print("The minimum element in the array is: ",np.min(arr)," and present on index: ",np.argmin(arr))
print("The maximum value of elements row wise: ",np.max(arr,axis = 1))
print("The maximum value of elements column wise: ",np.max(arr,axis = 0))
print("The minimum value of elements row wise: ",np.min(arr,axis = 1))
print("The minimum value of elements row wise: ",np.min(arr,axis = 0))
print("\nThe sum of all element of the array is: ",np.sum(arr))
a = np.sum(arr,axis=1)
print("Sum of element row wise",a)
b = np.sum(arr,axis = 0)
print("The sum of element Column wise: ",b)
print("The cumulative sum of elements of arrays is: ",np.cumsum(arr))
print("The cumulative product of element of array is: ",np.cumprod(arr))


[[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]
The maximum element in the array is:  16  and present on index:  7
The minimum element in the array is:  1  and present on index:  8
The maximum value of elements row wise:  [13 12 16]
The maximum value of elements column wise:  [ 9 16 13]
The minimum value of elements row wise:  [6 9 1]
The minimum value of elements row wise:  [ 6 10  1]

The sum of all element of the array is:  85
Sum of element row wise [31 31 23]
The sum of element Column wise:  [21 38 26]
The cumulative sum of elements of arrays is:  [ 6 18 31 40 50 62 68 84 85]
The cumulative product of element of array is:  [       6       72      936     8424    84240  1010880  6065280 97044480
 97044480]


8. random.shuffle(array_name) => it just changes the position of all elemnts in the array. this method is a part of random module.

9. unique(array_name) => it returns a different array from the original array, by removing all Duplicate elements of the array.

10. unique(array_name).size => rteurns the counts of number of unique elemnts present in the array.



In [ ]:
import numpy as np
np.random.seed(122)
arr = np.random.randint(1,21,5)
print(arr)
np.random.shuffle(arr)
print(arr)
arr1 = np.unique(arr)
print(arr1)
a = np.unique(arr).size
print(a)


[16 11 13 17 13]
[11 16 13 13 17]
[11 13 16 17]
4


NOTE:

numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)

Parameters:
ar: Input array.

return_index: If True, returns the indices of the first occurrence of the unique values in the input array.

return_inverse: If True, returns the indices to reconstruct the original array from the unique array.

return_counts: If True, returns the count of each unique element i.e frequency of each unique element.

axis: If specified, finds unique elements along the specified axis.

In [65]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(1,21,9)
print(arr)
arr1 = np.unique(arr,return_index=True,return_counts=True)# return_index gives the indexes of uninque element, return_count returns the occurence of elemnts.
print(arr1)

[ 6 12 13  9 10 12  6 16  1]
(array([ 1,  6,  9, 10, 12, 13, 16], dtype=int32), array([8, 0, 3, 4, 1, 2, 7]), array([1, 2, 1, 1, 2, 1, 1]))
