Reshaping of array: we use reshape() function to it, reshaping means to convert an array from one dimension to other.
eg: 1d to 2d array or vice versa.

synatax:
array_name.reshape(new_shape) 

here the argument passed is in the form of tuple, i.e no of elemnts same.

NOTE:
while rehaping the number of elemnts in original array must be same after reshaping.
eg: if an array have 12 elements then the total combination to convert it in 2d array is":
(4,3),(6,2),(2,6),(3,4) 

Conversion of 1D array into 2D array

In [3]:
import numpy as np
arr = [1,2,3,4,5,6,7,8,9,10,11,12]
arr = np.array(arr)
arr1=arr.reshape(4,3)
print(arr1)
print("Dimension of the new array is: ",arr1.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension of the new array is:  2


Conversion of 2D array into 1D array


In [2]:
import numpy as np
arr = np.array([[10,20,30,40],[80,90,100,120]])
arr1 = arr.reshape(8)
print(arr1)

[ 10  20  30  40  80  90 100 120]


COversion of 2D array into 3D array

In [1]:
import numpy as np
arr = np.array([[10,30,60,78],[89,45,68,69]])
arr = arr.reshape(2,2,2)
print(arr)
print("the dimension of new array is: ",arr.ndim)

[[[10 30]
  [60 78]]

 [[89 45]
  [68 69]]]
the dimension of new array is:  3


using - 1 to infer or predict the dimension, her we only pass one arguments for the 2d array, it automatically predicts the dimension for it.

In [23]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr1 = arr.reshape(-1,2) # here compiler will automatically calculate the no of rows.
arr2 = arr.reshape(3,-1)
arr3 = arr.reshape(2,1,-1)
print("first array: \n",arr1)
print("Second array: \n",arr2)
print("THird array: \n",arr3)
print("Dimension1: ",arr1.shape)
print("Dimension2: ",arr2.shape)
print("Dimension3: ",arr3.shape)

first array: 
 [[1 2]
 [3 4]
 [5 6]]
Second array: 
 [[1 2]
 [3 4]
 [5 6]]
THird array: 
 [[[1 2 3]]

 [[4 5 6]]]
Dimension1:  (3, 2)
Dimension2:  (3, 2)
Dimension3:  (2, 1, 3)
