In [6]:
import numpy as np
a = np.arange(1,16)
print(a)
a>10

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b = arr>10
print(arr[b])
print(arr[arr<5])

[11 12 13 14 15]
[1 2 3 4]


In [15]:
import numpy as np
arr = np.arange(1,16)
print(arr)
print("all even elements in the array are: ")
op = arr%2==0
print(arr[op])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
all even elements in the array are: 
[ 2  4  6  8 10 12 14]


In [19]:
import numpy as np
arr = np.arange(1,16)
print(arr)
print("assgning 0 to all even elements in the array are: ")
arr[arr%2==0]= 0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
assgning 0 to all even elements in the array are: 
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15]
