Indexing in pyhton starts from 0 from left to right.
In pyhton array also supports -ive indexing starts from -1 right to left 

In [12]:
import numpy as np
arr = np.array([10,20,40,56,68])
for i in range(arr.size):
    print(arr[i])
print(arr[-3])
sum =0
for i in range(0,arr.size,1):
    sum+=arr[i]
print("Sum of all elements of the array is: ",sum)  
product = 1
for i in range(0,arr.size,2):# product of all elements at even indexes.
    product*=arr[i]
print("Product of all elemnts is: ",product)  

10
20
40
56
68
40
Sum of all elements of the array is:  194
Product of all elemnts is:  27200


Array slicing, it is similar to list slicing.
Syntax:

array_name[start,end,step]


In [11]:
import numpy as np
n = int(input("Enter the siize of the array: "))
myarr=[]
for i in range(n):
    val = int(input())
    myarr.append(val)
arr = np.array(myarr)
arr1 = arr[2:5]
arr2 = arr[::-1]
arr3 = arr[4:]
print(arr1)
print(arr2)
print(arr3)

[30 40 50]
[70 60 50 40 30 20 10]
[50 60 70]
