1. zeroes=> it is used to create an array eith 1D or mutidimension, and fill all the elements as 0.

NOTE: array in numpy is by default float64 , hence we will get the values as float.

In [6]:
import numpy as n
arr1 = n.zeros(5)# creates a 1D array with size 5.
arr2 = n.zeros((2,3))# creates a 2d array with 2X3 shape.
print("Dimension of array 1 is: ",arr1.ndim)
print(arr1)
print("Dimension of array 2 is: ",arr2.ndim)
print(arr2)

Dimension of array 1 is:  1
[0. 0. 0. 0. 0.]
Dimension of array 2 is:  2
[[0. 0. 0.]
 [0. 0. 0.]]


2. ones => it is similar to zeroes function but it fills all th e values with 1.

In [18]:
import numpy as n
arr = n.ones(5)# 1 d array.
arr1 = n.ones((2,5))# creates a 2d array.
print("Elements of arr: \n",arr)
print("Elements of arr1: \n",arr1)

Elements of arr: 
 [1. 1. 1. 1. 1.]
Elements of arr1: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3. eye => it cretes an array with all diagonal element as 1 and rest of the elements as 0.

NOTE: if the non square matrix it their then the diagonal elements are 1(uptill where the diagonal can be drawn) and rest elemts are 0.

In [16]:
import numpy as n
arr = n.eye(3)
print("Dimension of the array is: ",arr.ndim)
print(arr)
arr1 = n.eye(3,4)
print("Dimension of the array is: ",arr1.ndim)
print(arr1)


Dimension of the array is:  2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimension of the array is:  2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Note: even you insert only one argument in eye function then also it makes a sqyare matrix of that size.

4. diag=> it takes an input as an array having value of each diagonal elements and rest of the elements as 0, it creates the square matrix accoring to number of diagonal elements. 

In [21]:
import numpy as n
arr = n.diag([20,40,60,80])
print(arr)
# to extract or get all the diagonal elements of any array we use diag(array_name)
n.diag(arr)

[[20  0  0  0]
 [ 0 40  0  0]
 [ 0  0 60  0]
 [ 0  0  0 80]]


array([20, 40, 60, 80])

5. randint=> this function is used to generate a random number(integer) b/w a given range in the form of a number or an array.


Syntax: 


        random.randint(min,max,size or no of values)

In [40]:
import numpy as np

# Single random integer
print(np.random.randint(1, 10))  # Output: A random integer between 1 (inclusive) and 10 (exclusive)

# 1D array of random integers
print(np.random.randint(1, 10, size=5))  # Output: [2, 6, 9, 3, 5]

# 2D array of random integers
print(np.random.randint(1, 10,(2, 3)))

2
[3 5 1 9 6]
[[8 8 7]
 [3 3 1]]


6. rand => 
this function generates random number b/w ranges [0,1)
** range: [0,1) is always fixed.
Synatax:

random.rand(no_of_elements)

In [ ]:
import numpy as n
print(n.random.rand(5))
# gives an 1D array of any random 5 float values
print(n.random.rand(2,3)) 
# given a 2d array of any random float values b/w [0.1)


[0.92388576 0.56633011 0.34182098 0.58258955 0.85172965]
[[0.20769185 0.36992796 0.7355126 ]
 [0.31121183 0.15295366 0.90076687]]


7. randn => this function getnerates random float values near 0.
the values may be positive or negative.'
syntax:

random.randn(no_of_values)


In [44]:
import numpy as n
print(n.random.randn())
print(n.random.randn(5))
# gives an 1D array of any random 5 float values near 0.
print(n.random.randn(2,3)) 
# given a 2d array of any random float values near 0.


-1.6647898978002256
[-0.62191423 -0.10444538 -0.64356623  0.12817356 -0.42348743]
[[ 0.63744328  0.68144305 -0.54621755]
 [-0.67795596  0.16748532  0.00740455]]


8. seed => this method is similar to randint() but the difference is that it keeps the value fixed after the random number generation. no matter how many time you run the program.

In [74]:
import numpy as np
np.random.seed(200) # no matter what integer value you are passing in seed function,
# but if any value is not passed in seed function the the value will be changed if you runt he program again.
#seed is also a part of random module.
arr = np.random.randint(1,100,10)
print(arr)

[27 17 69 43 56 77 80 90 15 92]


Note: the value is seed is fixed, until the arguments passed int the seed function doesn't change.