Different mathematical operation on 1D array.
NOTE: it does not effect the original array. 

In [14]:
import numpy as np
arr = np.arange(1,5)
arr1 = arr*2
print(arr1)
arr2 = arr+2
print(arr2)
arr3 = arr-2
print(arr3)
arr4 = arr/2
print(arr4)
arr5 = arr//2
print(arr5)
arr6 = arr/0
print(arr6)

[2 4 6 8]
[3 4 5 6]
[-1  0  1  2]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[inf inf inf inf]


C:\Users\Praneet Raj\AppData\Local\Temp\ipykernel_13308\1990099563.py:13: RuntimeWarning: divide by zero encountered in divide
  arr6 = arr/0


NOTE: in numpy if you divide any elemnt of array by 0 it doesn't give you error, instead of it, gives inf.

Adding two 1D array
, but must have same no of elemnts in both array.

In [17]:
import numpy as np
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
print(arr1+arr2)

[ 6  8 10 12]


Mathematical operation on 2d array

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4]).reshape(2,2)
print(arr1*2)
print(arr1/2)
print(arr1//2)
print(arr1**2)
print(arr1/0)

[[2 4]
 [6 8]]
[[0.5 1. ]
 [1.5 2. ]]
[[0 1]
 [1 2]]
[[ 1  4]
 [ 9 16]]
[[inf inf]
 [inf inf]]


C:\Users\Praneet Raj\AppData\Local\Temp\ipykernel_13308\34490594.py:7: RuntimeWarning: divide by zero encountered in divide
  print(arr1/0)


Addition of two 2D array

In [29]:
import numpy as np
arr1 = np.array([1,2,3,4]).reshape(2,2)
arr2 = np.array([5,6,7,8]).reshape(2,2)
print(arr1+arr2)
print("Multiplication of both matrices.")
print(arr1*arr2)
print("The matrix multiplication of two matrices: ")
print(arr1.dot(arr2))
print("division of two matrices: ")
print(arr1/arr2)


[[ 6  8]
 [10 12]]
Multiplication of both matrices.
[[ 5 12]
 [21 32]]
The matrix multiplication of two matrices: 
[[19 22]
 [43 50]]
division of two matrices: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
