In [6]:
import numpy as np
np.random.seed()
arr = np.random.randint(10,21,9)
print(arr)
arr1 = arr.reshape(3,3)
print("Array after reshaping: \n",arr1)

[11 14 15 12 12 13 15 15 18]
Array after reshaping: 
 [[11 14 15]
 [12 12 13]
 [15 15 18]]


convert all even values of an array to 0

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr[1::2]=0
print("After conevrting all even number to zero: ")
print(arr)

After conevrting all even number to zero: 
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


create an array of size 10 ,each value of array should be 5.

In [18]:
import numpy as np
arr = []
for i in range(10):
    val = 5
    arr.append(5)
arr = np.array(arr)
print(arr)
print(np.size(arr))

[5 5 5 5 5 5 5 5 5 5]
10


creat a 2d array of size 3X3 but all the elemnts should be b/w 0 to 1.

In [31]:
import numpy as np
arr = np.random.rand(9).reshape(3,3)
arr = np.array(arr)
print(arr)

[[0.11474597 0.94948926 0.44991213]
 [0.57838961 0.4081368  0.23702698]
 [0.90337952 0.57367949 0.00287033]]


perform array slicing 2D array i.e

arr = [[1,2,3,4],

        [5,6,7,8],

        [9,10,11,12],

        [13,14,15,16]]

to get the deisired output as: 

[[ 6  7]

 [10 11]

 [14 15]]


In [38]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr1 = arr[1:,1:3]
print(arr1)

[[ 6  7]
 [10 11]
 [14 15]]


Concatenate 2D array and concatenate them horizontallay and vertically.

In [42]:
import numpy as np
np.random.seed(2)
arr = np.random.randint(1,21,9).reshape(3,3)
arr1 = np.random.randint(20,51,9).reshape(3,3)
print("The original array is: \n",arr,"\n\n",arr1,"\n")
hori = np.hstack((arr,arr1))
ver = np.vstack((arr,arr1))
print("Horizontal Stacking: \n",hori)
print("Vertical Stacking: \n",ver)

The original array is: 
 [[ 9 16 14]
 [ 9 12 19]
 [12  9  8]] 

 [[22 37 31]
 [41 35 46]
 [40 48 40]] 

Horizontal Stacking: 
 [[ 9 16 14 22 37 31]
 [ 9 12 19 41 35 46]
 [12  9  8 40 48 40]]
Vertical Stacking: 
 [[ 9 16 14]
 [ 9 12 19]
 [12  9  8]
 [22 37 31]
 [41 35 46]
 [40 48 40]]
