where(arr==element) => this method returns an array having index of the each occurence of that particular element in whole array.

In [11]:
import numpy as np
arr = np.array([1,2,35,40,50,67,70,40,40])
# arr.sort()
print(arr)
a = np.unique(arr).size
print("Number of unique elements in the array is: ",a)
x = np.where(arr==40)
print(x)
even_numbers = np.where(arr%2==0)
print(even_numbers)

[ 1  2 35 40 50 67 70 40 40]
Number of unique elements in the array is:  7
(array([3, 7, 8]),)
(array([1, 3, 4, 6, 7, 8]),)


SearchSorted(arr,element)=> this method performs binary search, and returns the index where the specified value should be inserted to maintain the order.

In [17]:
import numpy as np
arr = np.array([2,5,8,9,13])# sorted array is provided
x = np.searchsorted(arr,7)# by default the searching starts from left to right.
# arr is the array name, 7 is the element to be inserted.
print(x)
# performing searchsorted from right to left
x1 = np.searchsorted(arr,7,side='right')
print(x1)# output will remain same always.

2
2
