creating 2d array using user input

In [3]:
import numpy as np
matrix=[]
row = int(input("Enter the no of rows: "))
col = int(input("Enter no of columns: "))
for i in range(row):
    a = []
    for j in range(col):
        val = int(input())
        a.append(val)
    matrix.append(a)
arr = np.array(matrix)
print("The element of array are: ")
for i in range(row):
    for j in range(col):
        print(matrix[i][j],end = ' ')
    print()

The element of array are: 
10 20 30 
40 50 60 
70 80 90 


Slicing in 2D array

In [9]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[:2])
print("second slicing ",end = ' ')
print(arr[1:2,0:1])
print("third slicing ")
print(arr[:3,:2])


[[10 20 30]
 [40 50 60]]
second slicing  [[40]]
third slicing 
[[10 20]
 [40 50]
 [70 80]]


Seed operation on 2D array

In [26]:
import numpy as np
arr = []
np.random.seed(111)
arr = np.random.randint(1,500,20).reshape(4,5)
# NOTE: here the total no of elemenst in randint should must be same in reshaping. 
print(arr)
print("After slicing",end = '\n')
print(arr[2:,2:])

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]]
After slicing
[[442   8 269]
 [369 217 285]]
