In [19]:
import numpy as np
arr1 = np.array([12,45,67]) 
arr2 = np.array([23,67,89])
result1 = np.hstack((arr1,arr2))
result2 = np.vstack((arr1,arr2))
print("Horizontal stacking: ",result1)
print("Vertical stacking: \n",result2)
result3 = np.dstack((arr1,arr2))
print("Depth stack: \n",result3)
print("using universal Stack function: ")
result4 = np.stack((arr1,arr2),axis =0)
print(result4)
result5 = np.stack((arr1,arr2),axis=1)
print(result5)

Horizontal stacking:  [12 45 67 23 67 89]
Vertical stacking: 
 [[12 45 67]
 [23 67 89]]
Depth stack: 
 [[[12 23]
  [45 67]
  [67 89]]]
using universal Stack function: 
[[12 45 67]
 [23 67 89]]
[[12 23]
 [45 67]
 [67 89]]


Stacking in 2d array

In [26]:
import numpy as np
np.random.seed(1)
arr1 = np.random.randint(1,21,9).reshape(3,3)
arr2 = np.random.randint(50,71,9).reshape(3,3)
print("Array 1 => \n",arr1)
print("Array 2 => \n",arr2)
print("Array after hstack=> \n",np.hstack((arr1,arr2)))
print("Array after vertical stacking=> \n",np.vstack((arr1,arr2)))

Array 1 => 
 [[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]]
Array 2 => 
 [[66 51 62]
 [57 63 56]
 [68 70 55]]
Array after hstack=> 
 [[ 6 12 13 66 51 62]
 [ 9 10 12 57 63 56]
 [ 6 16  1 68 70 55]]
Array after vertical stacking=> 
 [[ 6 12 13]
 [ 9 10 12]
 [ 6 16  1]
 [66 51 62]
 [57 63 56]
 [68 70 55]]
