Creting a 2D array using array method of numpy package 


In [2]:
import numpy as np
a = [[19,29,30],[48,98,78],[78,67,57]]
myarr = np.array(a)
print(myarr)

[[19 29 30]
 [48 98 78]
 [78 67 57]]


We can also create a 2d array by directly inserting values in array() method

In [3]:
import numpy as ab
arr = ab.array([[10,20,30],[68,45,89],[87,45,67]])
print(arr)

[[10 20 30]
 [68 45 89]
 [87 45 67]]


ndim function=> return the dimension of the array.

In [4]:
import numpy as np
a = [[19,29,30],[48,98,78],[78,67,57]]
myarr = np.array(a)
print(myarr)
print("The dimension of the array is: ",arr.ndim)

[[19 29 30]
 [48 98 78]
 [78 67 57]]
The dimension of the array is:  2


shape function=> it returns the shape of the array, i.e now of rows and columns in form of (rows,columns)

In [5]:
import numpy as np
a = [[19,29,30],[48,98,78],[78,67,57]]
myarr = np.array(a)
print(myarr)
print("The shape of the array is: ",arr.shape)

[[19 29 30]
 [48 98 78]
 [78 67 57]]
The shape of the array is:  (3, 3)
